### ISSUE TITLE
New API key

### ISSUE THREAD

**Issue by hejjoe** [JimVincentW/open-politics#5]
https://github.com/JimVincentW/open-politics/blob/07c2de12184f3f0b7ac9e48ad94099a21b050eaf/README.md?plain=1#L174

> Zur Nutzung ist ein API-Key notwendig. Der zunächst bis Ende Mai 2025 gültige API-Key lautet:
> I9FKdCn.hbfefNWCY336dL6x62vfwNKpoN2RZ1gp21
> 
> Auf Anfrage können Sie auch einen eigenen API-Key mit einer Laufzeit von zunächst zehn Jahren erhalten. Ein eigener API-Key hat denselben Funktionsumfang wie der öffentliche API-Key.
> 
> Bitte stellen Sie eine diesbezügliche Anfrage per E-Mail an: [parlamentsdokumentation@bundestag.de](mailto:parlamentsdokumentation@bundestag.de) 

https://dip.bundestag.de/%C3%BCber-dip/hilfe/api#content

**Comment by JimVincentW** [comment]
Danke für das Update :) Key ist ausgetauscht. Kann übrigens genutzt werden im Globe bei Deutschland. Wird aber bald noch ausgebaut um tiefer in die Gesetze einzusteigen
